
language: rust
rust:
  - nightly

cache: cargo
dist: trusty
sudo: false

branches:
  only:
    - development

script:
  - export -- CARGO_TARGET_DIR=./target/default
  - ./.x-run.execute ':'':'' compile / all / debug'
  - ./.x-run.execute ':'':'' compile / clippy / debug'
  - ./.x-run.execute ':'':'' execute / bin / tester / all / debug'

